executors:
  pytest:
    docker:
      - image: databricksdocs/pytest:v0.1.5
        commands:
        - pip install -r requirements.txt
        - pytest

kind: pipeline
type: docker
name: default



