kind: pipeline
type: docker
name: default


steps:
  - name: pytest
    image: databricksdocs/pytest:v0.1.5
    commands:
    - pip install -r requirements.txt
    - pytest

  - name: gitleaks
    image: zricethezav/gitleaks:latest
    commands:
    - gitleaks detect -v

  - name: pylint
    image: wpengine/pylint:latest
    commands:
    - pip install -r requirements.txt
    - pylint flaskr --errors-only

  - name: sonarqube
    image: aosapps/drone-sonar-plugin
    settings:
      sonar_host:
        from_secret: sonar_host
      sonar_token:
        from_secret: sonar_token

  - name: jfrog
    image: ateret/jfrog-cli:v4
    commands: 
    - apk add py3-pip
    - jf c add default --artifactory-url $frog_host --access-token $frog_token
    - jf pip-config --server-id-resolve default --repo-resolve pypi-remote
    - jf pip install -r requirements.txt --build-name=FlaskBuild --build-number=$DRONE_BUILD_NUMBER
    environment:
      frog_host:
        from_secret: frog_host
      frog_token:
        from_secret: frog_token
    




