kind: pipeline
type: docker
name: default


steps:
  - name: pytest
    image: databricksdocs/pytest:v0.1.5
    commands:
    - pip install -r requirements.txt
    - pytest

  - name: publish
    image: plugins/docker
    settings:
      repo: plugins/gitleaks
      auto_tag: true
      dockerfile: docker/Dockerfile
      username:
        from_secret: docker_username
      password:
        from_secret: docker_password

  





