kind: pipeline
type: docker
name: default


steps:
  - name: pytest
    image: databricksdocs/pytest:v0.1.5
    commands:
    - pip install -r requirements.txt
    - pytest

  - name: gitleaks
    image: zricethezav/gitleaks:latest

  - name: pylint
    image: pipelinecomponents/pylint
    




