executors:
  pytest:
    docker:
      - image: databricksdocs/pytest:v0.1.5

kind: pipeline
type: docker
name: default

steps:
- name: test
  image: python
  commands:
  - pip install -r requirements.txt
  - pytest

